fix for cyclic inclusion issue of stun.h in stunrequest.h
when compiling kopete/protocols/jabber/googletalk/libjingle/talk/session/phone/channelmanager.cc
it would produce this error:

kopete/protocols/jabber/googletalk/libjingle/talk/p2p/base/stunrequest.h:91:9: error: ‘StunMessageType’ does not name a type

problem:
  this is cased by a cyclic use of stun.h, stunrequest.h and channelmanager.cc with the outcome,
  that kdenetwork couldn't be compiled since kopete fails to build.

solution:
  move the StunMessageType enum into its own #ifndef