.libs/yahooprotocol.o: In function `YahooProtocol::YahooProtocol(QObject *, char const *, QStringList const &)': /home/martijn/src/kde3/kdenonbeta/kopete/protocols/yahoo/yahooprotocol.cpp:57: undefined reference to `YahooProtocol::init(void)'
Is everone else using CVS HEAD with the broken am_edit/libtool/whatever that
doesn't detect missing symbols? And, is there any chance to fix that? What
exactly causes this problem?

svn path=/trunk/kdenetwork/kopete/; revision=174785